// <auto-generated />
namespace DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class AltNavigatPropGymsId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AltNavigatPropGymsId));
        
        string IMigrationMetadata.Id
        {
            get { return "202002081603551_Alt-NavigatProp-GymsId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
